name: getx_template
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_lints: ^4.0.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  path: ^1.9.0
  geolocator: ^13.0.1
  mask_text_input_formatter: ^2.9.0
  flutter_local_notifications: ^17.2.2
  get_storage: ^2.1.1
  #google_mobile_ads: ^5.1.0
  flutter_fortune_wheel: ^1.3.1
  scratcher: ^2.5.0
  intl: ^0.19.0
  flutter_localization: ^0.2.2
  upgrader: ^11.2.0
  in_app_review: ^2.0.9
  share_plus: ^10.1.1
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  animated_bottom_navigation_bar: ^1.3.3
  
  #firebase
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.4
  firebase_analytics: ^11.3.4
  firebase_auth: ^5.3.2
  firebase_storage: ^12.3.5
  firebase_messaging: ^15.1.4
  cloud_firestore: ^5.4.5
  cloud_functions: ^5.1.4
  firebase_remote_config: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/data/
